baseURL = "https://ynki.website/"
languageCode = "en-us"
title = "Ynki"
theme = "ezhil"
enableRobotsTXT = true

copyright = "Â© Copyright notice"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-123-45"
# Your Disqus sortname.
disqusShortname = "ynki"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Number of characters to show in summary.
summaryLength = 20

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "In the darkness of bugs, I forge clarity."
    description = "Expert software engineering and AI development services focused on mobile apps, web platforms, system-level tools, and high-            performance backend solutions."
    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/myicon.png"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "dark" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
    customDarkCSS = "css/custom-dark.css"

keywords = [
  "software development services",
  "custom software solutions",
  "AI development",
  "reverse engineering expert",
  "mobile app development",
  "backend developer for hire",
  "web platform development",
  "high-performance systems",
  "Windows/Linux driver development",
  "cross-platform mobile apps",
  "API integration and design",
  "scalable backend architecture",
  "AI consulting services",
  "real-time systems developer",
  "API development",
  "web development",
  "UI/UX design",
  "mobile apps",
  "desktop applications"
]
    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
    customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]



# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "https://ynki.website/"
weight = 1


# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).

# hugo.toml
baseURL = "https://ynki.website/"
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true






